# docker-compose -p shard -f mongodb-shard-cluster.yml up
# 

version: '3'
services:
  rs0:
    container_name: rs0
    image: "mongo:3.4"
    volumes:
      - ./data/mongodb/r0:/data/db
    restart: always
    expose:
      - "27017:27019"
    entrypoint: [ "/usr/bin/mongod", "--replSet", "shard0", "--shardsvr", "--smallfiles", "--oplogSize", "128"]
  rs1:
    container_name: rs1
    image: "mongo:3.4"
    volumes:
      - ./data/mongodb/r1:/data/db
    restart: always
    expose:
      - "27017:27019"
    entrypoint: [ "/usr/bin/mongod",  "--replSet", "shard0", "--shardsvr", "--smallfiles", "--oplogSize", "128"]
  rs2:
    container_name: rs2
    image: "mongo:3.4"
    volumes:
      - ./data/mongodb/r2:/data/db
    restart: always
    expose:
      - "27017:27019"
    entrypoint: [ "/usr/bin/mongod", "--replSet", "shard0", "--shardsvr", "--smallfiles", "--oplogSize", "128"]


  conf0:
    container_name: conf0
    image: "mongo:3.4"
    volumes:
      - ./data/mongodb/c0:/data/db
    restart: always
    expose:
      - "27017:27019"
    entrypoint: [ "/usr/bin/mongod", "--replSet", "cnf0", "--configsvr", "--smallfiles", "--oplogSize", "10"]
  conf1:
    container_name: conf1
    image: "mongo:3.4"
    volumes:
      - ./data/mongodb/c1:/data/db
    restart: always
    expose:
      - "27017:27019"
    entrypoint: [ "/usr/bin/mongod",  "--replSet", "cnf0", "--configsvr", "--smallfiles", "--oplogSize", "10"]
  conf2:
    container_name: conf2
    image: "mongo:3.4"
    volumes:
      - ./data/mongodb/c2:/data/db
    restart: always
    expose:
      - "27017:27019"
    entrypoint: [ "/usr/bin/mongod", "--replSet", "cnf0", "--configsvr", "--smallfiles", "--oplogSize", "10"]

  mongos0:
    container_name: mongos0
    image: "mongo:3.4"
    restart: always
    expose:
      - "27017:27019"
    entrypoint: [ "/usr/bin/mongos", "--configdb", "cnf0/conf0:27019,conf1:27019,conf2:27019"]

  mongos1:
    container_name: mongos1
    image: "mongo:3.4"
    restart: always
    expose:
      - "27017:27019"
    entrypoint: [ "/usr/bin/mongos", "--configdb", "cnf0/conf0:27019,conf1:27019,conf2:27019"]
