# docker-compose -p opsmgr -f mongodb-ops-manager.yml up
#
version: '3'
services:
  appmongo:
    container_name: appmongo
    image: mongo:3.4
    environment:
      - TZ="Asia/Manila"
  
  backupmongo1:
    container_name: backupmongo1
    image: mongo:3.4
    environment:
      - TZ="Asia/Manila"
        #    command: --replSet "backupmongo"

    #  backupmongo2:
    #    container_name: backupmongo2
    #    image: mongo:3.4
    #    environment:
    #      - TZ="Asia/Manila"
    #      - DNSDOCK_ALIAS=backupmongo2.docker
    #    dns: ["172.17.0.1"]
    #    command: --replSet "backupmongo"
    #
    #  backupmongo3:
    #    container_name: backupmongo3
    #    image: mongo:3.4
    #    environment:
    #      - TZ="Asia/Manila"
    #    command: --replSet "backupmongo"
  
  opsmanager:
    container_name: opsmanager
    image: gengame/mongodb-ops-manager:1.2.0-SNAPSHOT
    expose:
      - "8080"
    environment:
      - TZ="Asia/Manila"
      - OPSMANAGER_MONGO_APP=mongodb:\/\/appmongo:27017\/?maxPoolSize=100
#      - OPSMANAGER_BACKUPMONGO=backupmongo1.docker:27017,backupmongo2.docker:27017,backupmongo3.docker:27017/?maxPoolSize=100&replicaSet=backupmongo
#      - OPSMANAGER_BACKUPMONGO=backupmongo1.docker:27017/?maxPoolSize=100
      - OPSMANAGER_CENTRALURL=http:\/\/opsmanager:8080
      - OPSMANAGER_CENTRALURLPORT=8080
      - OPSMANAGER_GEN_KEY=UlzOcc6qCoKqPcyDtlbuQQ1ajbHuB30x
      - OPSMANAGER_FROMEMAIL=jeff.f@gen-game.com
      - OPSMANAGER_ADMINEMAIL=jeff.f@gen-game.com
      - OPSMANAGER_REPLYTOEMAIL=jeff.f@gen-game.com
      - OPSMANAGER_BOUNCEEMAIL=jeff.f@gen-game.com
      - OPSMANAGER_EMAILDAO=com.xgen.svc.core.dao.email.JavaEmailDao
      - OPSMANAGER_MAIL_TRANSPORT=smtps
      - OPSMANAGER_MAIL_HOSTNAME=gmail.com
      - OPSMANAGER_MAIL_PORT=465
      - OPSMANAGER_MAIL_USERNAME=email
      - OPSMANAGER_MAIL_PASSWORD=email
      - OPSMANAGER_MAIL_USETLS=true
      - OPSMANAGER_ROOTDIRECTORY=\/head\/
    volumes: 
      - $PWD/data/head:/head
      - $PWD/data/snapshot:/snapshot
  
  node1:
    container_name: node1
    hostname: node1
    image: centos:7.4.1708
    environment:
      - TZ="Asia/Manila"
    expose:
      - "27000-28000"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /tmp
    cap_add:
      - ALL
    entrypoint:
      - /usr/sbin/init

  node2:
    container_name: node2
    hostname: node2
    image: centos:7.4.1708
    environment:
      - TZ="Asia/Manila"
    expose:
      - "27000-28000"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /tmp
    cap_add:
      - ALL
    entrypoint:
      - /usr/sbin/init

  node3:
    container_name: node3
    hostname: node3
    image: centos:7.4.1708
    environment:
      - TZ="Asia/Manila"
    expose:
      - "27000-28000"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /tmp
    cap_add:
      - ALL
    entrypoint:
      - /usr/sbin/init

  agent:
    container_name: agent
    image: centos:7.4.1708
    environment:
      - TZ="Asia/Manila"
    expose:
      - "27000-28000"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /tmp
    cap_add:
      - ALL
    entrypoint:
      - /usr/sbin/init

  java:
    container_name: java
    image: "openjdk:8"
    volumes:
      - $PWD:/java
    entrypoint: [ "tail", "-f", "/dev/null"]

